[2022-05-03 09:27:17,532] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:27:23,355] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:27:23,662] [views.py:233] [views:update_cooperation_info] [ERROR]- Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 228, in update_cooperation_info
    update_cooperation_data(cooperation_id, cur_db_util, json.loads(request.body))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py", line 62, in update_cooperation_data
    logging.INFO(sql_str)
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 228, in update_cooperation_info
    update_cooperation_data(cooperation_id, cur_db_util, json.loads(request.body))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py", line 62, in update_cooperation_data
    logging.INFO(sql_str)
TypeError: 'int' object is not callable
[2022-05-03 09:27:23,663] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:27:23,664] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:29:13,531] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 09:29:14,567] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:29:23,975] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 09:29:24,468] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:29:27,361] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:29:28,121] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:29:28,122] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:30:00,256] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 09:30:00,743] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:30:04,193] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:30:04,511] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:30:04,512] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:30:54,806] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 09:30:55,300] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:30:57,327] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:30:57,573] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:30:57,574] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:30:58,560] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:30:58,849] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:30:58,850] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:31:06,753] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 09:31:07,479] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:31:29,006] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 09:31:29,617] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:31:33,862] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:31:34,209] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:31:34,210] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:31:35,025] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:31:35,289] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:31:35,291] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:31:40,030] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 09:31:40,771] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:31:51,212] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 09:31:51,757] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:31:53,903] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:31:54,063] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:31:54,064] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:31:55,001] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:31:55,164] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:31:55,166] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:31:56,198] [decorators.py:42] [decorators:wrapper] [INFO]- {'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十有一', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'store_id': '22222245', 'goods_id': 8, 'anchor_openid': 'oJ92T5adaBqYeg9lC_9ouxHKoHfQ', 'commission_rate': '35.5', 'pos_price': '5000', 'store_name': '倪攀', 'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:31:56,344] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:31:56,345] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:32:20,013] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:32:20,123] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:32:20,127] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 09:32:55,930] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 09:32:56,805] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 09:34:06,647] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 09:34:06,917] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 09:34:06,918] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:14:26,819] [decorators.py:42] [decorators:wrapper] [INFO]- {'store_id': '999', 'goods_url': 'https://item.jd.com/100030291368.html', 'pic_path': ['https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg', 'https://img30.360buyimg.com/sku/jfs/t1/200456/25/20481/184777/61b8a292E325a6ca9/79021d299865b2b9.jpg'], 'live_recording_screen_path': 'https://jvod.300hu.com/vod/product/5c59e1dd-5ef4-4046-995a-88d4e73653b9/eb7adb4d179443c09c91953b65108a08.mp4?source=2&h265=h265/18799/6281e15a04d443c38b3392427d62a6b4.mp4', 'brand': 'MC', 'goods_name': 'T5真无线蓝牙耳机降噪双耳入耳式运动跑步迷你隐形游戏通用于华为苹果vivo小米oppo荣耀手机 迈从T5尊贵黑（智能数显/高清镜面/9D音效）', 'specification': '240g（16包左右）包邮', 'hand_card': '十三香虾尾优势： 1.方便快捷，开盖换碗加热即食 2.多种搭配（可做虾尾拌面/加入喜欢的蔬菜做炒菜/虾尾火鸡面等） 3.高标准严格清洗，整洁卫生，无需二次清理 4.肉质紧实，颗颗饱满 5.数十种香料秘制，汤汁爽辣，浓香四溢 6.人工筛选新鲜活虾，人工取尾，虾尾饱满q弹', 'storage_condition': '低温冷冻保存', 'shelf_life': '12', 'unsuitable_people': '老少皆宜', 'favorable_rate': '95.6', 'daily_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'lowest_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'tmall_price': '', 'taobao_price': '', 'other_price': '', 'live_price': '19.9/10包 29.8/15包 39.9/24包 49.9/30包', 'preferential_way': '限时秒杀', 'delivery_company': '物流公司：百世  中通  邮政  韵达  圆通，不接受指定快递', 'shipping_addresses': '安徽合肥', 'shipping_cycle': '现货48小时发出，预售7天内', 'free_shipping': '江浙沪', 'not_shipping': '无', 'comment': '', 'offline_price': '22222245', 'commission_rate': 22, 'pos_price': 223, 'ability_to_deliver': 33}
[2022-05-03 14:14:27,186] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 200, 'data': {'goods_id': 28}, 'msg': '添加商品成功'}
[2022-05-03 14:14:27,189] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /goods_manage/add_goods/ HTTP/1.1" 200 68
[2022-05-03 14:41:28,406] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:41:29,365] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:41:41,491] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:41:41,779] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:41:41,781] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:41:43,917] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:41:44,218] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:41:44,219] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:42:39,685] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:42:40,451] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:44:21,806] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:44:22,074] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:44:22,075] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:45:40,255] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 14:45:41,058] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:45:58,542] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 14:45:59,005] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:46:09,061] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:46:09,441] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:46:09,442] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:46:47,962] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:46:48,734] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:46:53,892] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:46:54,073] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:46:54,074] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:47:22,564] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:47:23,216] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:47:25,609] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:47:25,781] [views.py:234] [views:update_cooperation_info] [ERROR]- Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 228, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 228, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
[2022-05-03 14:47:25,786] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:47:25,787] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:48:24,568] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:48:25,285] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:48:31,786] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:48:31,793] [views.py:235] [views:update_cooperation_info] [ERROR]- Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 219, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
AttributeError: 'NoneType' object has no attribute 'execute'
Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 219, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
AttributeError: 'NoneType' object has no attribute 'execute'
[2022-05-03 14:48:31,794] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:48:31,795] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:48:52,950] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:48:53,762] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:48:56,226] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:48:56,474] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 450, 'data': '', 'msg': '修改合作单失败'}
[2022-05-03 14:48:56,475] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:49:20,474] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:49:21,029] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:49:22,892] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:49:23,081] [views.py:236] [views:update_cooperation_info] [ERROR]- Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 230, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 230, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
[2022-05-03 14:49:23,084] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:49:23,084] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:49:49,699] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:49:50,477] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:49:52,437] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:49:52,562] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 450, 'data': '', 'msg': '合作单不存在'}
[2022-05-03 14:49:52,564] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 54
[2022-05-03 14:50:04,934] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:50:05,892] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:50:12,162] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:50:12,377] [views.py:237] [views:update_cooperation_info] [ERROR]- Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 231, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 231, in update_cooperation_info
    print(cur_db_util.execute_single_sql_in_transaction("select * from cooperation"))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
[2022-05-03 14:50:12,381] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:50:12,381] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:50:51,920] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:50:52,667] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:50:54,071] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:50:54,422] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 450, 'data': '', 'msg': '修改合作单失败'}
[2022-05-03 14:50:54,424] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:51:00,065] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:51:00,594] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:51:02,294] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:51:02,591] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 450, 'data': '', 'msg': '合作单不存在'}
[2022-05-03 14:51:02,592] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 54
[2022-05-03 14:51:16,077] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:51:16,679] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:51:17,885] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:51:18,359] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:51:20,599] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:51:20,889] [views.py:233] [views:update_cooperation_info] [ERROR]- Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 228, in update_cooperation_info
    update_cooperation_data(cooperation_id, cur_db_util, json.loads(request.body))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py", line 64, in update_cooperation_data
    cur_db_util.execute_single_sql_in_transaction(sql_str)
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 228, in update_cooperation_info
    update_cooperation_data(cooperation_id, cur_db_util, json.loads(request.body))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py", line 64, in update_cooperation_data
    cur_db_util.execute_single_sql_in_transaction(sql_str)
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
[2022-05-03 14:51:20,892] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:51:20,893] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:51:31,796] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:51:32,337] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:51:33,865] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:51:35,300] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 200, 'data': '', 'msg': '合作单修改成功'}
[2022-05-03 14:51:35,304] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:51:45,836] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:51:46,439] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:51:51,563] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:51:52,136] [views.py:236] [views:update_cooperation_info] [ERROR]- Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 231, in update_cooperation_info
    update_cooperation_data(cooperation_id, cur_db_util, json.loads(request.body))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py", line 64, in update_cooperation_data
    cur_db_util.execute_single_sql_in_transaction(sql_str)
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py", line 231, in update_cooperation_info
    update_cooperation_data(cooperation_id, cur_db_util, json.loads(request.body))
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py", line 64, in update_cooperation_data
    cur_db_util.execute_single_sql_in_transaction(sql_str)
  File "/Users/fantasy/Downloads/nipan/wxcloudrun/utils/SQL/DBUtils.py", line 171, in execute_single_sql_in_transaction
    self.cursor.execute(sql_str)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fantasy/Downloads/nipan/venv/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')
[2022-05-03 14:51:52,140] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:51:52,141] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:52:37,368] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:52:37,875] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:52:39,085] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:52:39,554] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:52:41,569] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:52:42,008] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:52:42,011] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:52:48,952] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:52:49,492] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:52:51,093] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:52:51,508] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 200, 'data': '', 'msg': '合作单修改成功'}
[2022-05-03 14:52:51,509] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:53:41,566] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:53:42,374] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:53:49,675] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:53:50,185] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:53:56,426] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:53:56,714] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 200, 'data': '', 'msg': '合作单修改成功'}
[2022-05-03 14:53:56,715] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:53:58,399] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:53:58,736] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 200, 'data': '', 'msg': '合作单修改成功'}
[2022-05-03 14:53:58,737] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:54:10,839] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:54:11,540] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:54:23,862] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:54:24,194] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 200, 'data': '', 'msg': '合作单修改成功'}
[2022-05-03 14:54:24,196] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:54:38,276] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/cooperation_manage/views.py changed, reloading.
[2022-05-03 14:54:38,764] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:54:40,324] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:54:40,588] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:54:40,590] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:54:55,217] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 14:54:55,672] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:54:57,948] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:54:58,203] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:54:58,204] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:54:59,047] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:54:59,335] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:54:59,336] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:55:10,171] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 14:55:10,709] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:55:12,248] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:55:12,577] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 550, 'data': '', 'msg': '合作单修改异常'}
[2022-05-03 14:55:12,578] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
[2022-05-03 14:56:26,856] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/utils.py changed, reloading.
[2022-05-03 14:56:27,406] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:56:50,932] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /Users/fantasy/Downloads/nipan/wxcloudrun/mapper/cooperation.py changed, reloading.
[2022-05-03 14:56:51,392] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-05-03 14:56:53,720] [decorators.py:42] [decorators:wrapper] [INFO]- {'dsr': '12', 'cooperation_id': '33'}
[2022-05-03 14:56:54,102] [decorators.py:62] [decorators:wrapper] [INFO]- {'code': 200, 'data': '', 'msg': '合作单修改成功'}
[2022-05-03 14:56:54,104] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /cooperation_manage/update_cooperation_info/ HTTP/1.1" 200 57
